[package]
name = "figlet-font"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
thiserror = "1.0.25"
unicode-segmentation = "1.7.1"
unicode-width = "0.1.8"
